### PR TITLE
Update Dark Mode

### PR DESCRIPTION
**Pull request by jmlopez2332**
Dark Mode

### CODE REVIEW

**Comment by bhaumikmistry** [comment]
error "Uncaught ReferenceError: $ is not defined"
@jmlopez2332 are you using jQuery?

**Comment by jmlopez2332** [comment]
oh, yes,  i'm using jQuery
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

**Comment by jmlopez2332** [comment]
updated!

**Comment by bhaumikmistry** [comment]
every time a new contribution is added, those calls will have a different title, they have to be updated in the JS call as well, think about more generic way to use the invert, may of on the parent div?

**Comment by jmlopez2332** [comment]
do you mean use "div" in "filer invert"?

**Comment by bhaumikmistry** [comment]
Or may be just div with class Column? div would invert everything wouldn't it?

**Comment by jmlopez2332** [comment]
Your right!, a div with class column solve the problem

**Pull request merged**
