### PR TITLE
Implemented the flicker button - issue #50

### PR DESCRIPTION
**Pull request by janelbrandon**
Changes the background of image cells to random colors from a random color palette

Added flicker.js with the logic. It defines some color palettes from https://www.color-hex.com/color-palettes/. It selects one palette randomly, then for each img cell, it selects a random background color from the palette.

It also changes the background color of the button to yellow. I also changed the foreground color of the button to a darker number so there is sufficient contrast.

I also added an id to the flicker button to make it easier to add the event handler.

Please let me know if you would like any changes.

### CODE REVIEW

**Comment by janelbrandon** [comment]
Sorry! I'll fix the conflicts

**Comment by janelbrandon** [comment]
There are some issues with the dark-mode enhancement ... some null pointers. I'll raise an issue and fix those first, then I'll update this PR.

**Comment by bhaumikmistry** [comment]
- I resolved conflict locally, should i merge ?
- I don't see any null pointer issues after solving conflicts. Please advice on where exactly you are getting those errors? @janelbrandon

**Comment by janelbrandon** [comment]
I see you fixed it!

I've updated my PR to include your changes, and to take into account how flicker/dark-mode should behave when both are enabled. Let me know if you want me to make any changes! :)

**Comment by janelbrandon** [comment]
our spacing is different - I'm using VSCode extensions that space differently than what you have - so it makes the diff challenging. Sorry about that!

**Pull request merged**
